### ISSUE TITLE
Roadmap for deprecating bene_media

### ISSUE THREAD

**Issue by mariacha** [thinkshout/bene_media#35]
We are not using bene_media on new builds and are still supporting it for old builds only. This ticket brainstorms what steps would be required to remove bene_media entirely.

## End goal:
Use Drupal's built-in Media and Media Library, as well as Focal point and https://www.drupal.org/project/media_library_edit instead of Bene Media.

Some things that we'd lose:
- [ ] The Media Library is not a view that can be customized right now. You get what you get: https://www.drupal.org/docs/core-modules-and-themes/core-modules/media-library-module/customizing-the-media-library. But, if you don't use the Media Library Field Widget during upload, and just stick with the Media Entity Browser widget, you can still customize what view is used.
- [ ] The way items are uploaded and auto-distributed into the right media entity would change (right now there's just one field that turns an upload into an Image or a Document and in Media Library, you set that yourself.
- [ ] ... other things...

## Possible ways of attacking the problem
- [ ] Search your site's config for anything that depends on `bene_media` and make that config not depend on `bene_media` but use other modules instead. So for example,:
* if you have config that depends on the "bene_media" view, that's all fine and can continue to exist. 
* If you have an entity_browser plugin that depends on `bene_media` it's probably using on of the [provided widgets](https://github.com/thinkshout/bene_media/tree/8.x-2.x/src/Plugin/EntityBrowser/Widget), like file_upload. You can likely find a built-in plugin `EntityBrowserWidget` plugin that does almost the same thing.
* If you have a field that depends on `bene_media` it's probably using a the [custom image field widget](https://github.com/thinkshout/bene_media/tree/8.x-2.x/src/Plugin/Field/FieldWidget) (although an update hook in the 8.x-2.x-bene branch should have fixed that).
